name: 'build'

on:
  push:
    branches:
      - main
    tags:
      - '*'

jobs:

  msys2:
    runs-on: windows-latest
    strategy:
        fail-fast: false
        max-parallel: 2
        matrix:
          target: [
            { msys2: MINGW64, arch: x86_64}
          ]
    continue-on-error: false
    defaults:
      run:
        shell: msys2 {0}
    env:
      MINGW_ARCH: ${{ matrix.target.msys2 }}
    steps:

    - run: git config --global core.autocrlf input
      shell: bash

    - uses: actions/checkout@v3

    - uses: msys2/setup-msys2@v2
      with:
        update: true
        install: >
          base-devel
          git
          mingw-w64-${{ matrix.target.arch }}-toolchain
          mingw-w64-${{ matrix.target.arch }}-autotools
          mingw-w64-${{ matrix.target.arch }}-python
        msystem: ${{ matrix.target.msys2 }}

    - name: Install extra packages
      run: |
        msystem=$(echo "${{ matrix.target.msys2 }}" | tr '[:upper:]' '[:lower:]')
        ./install_packages.sh $msystem ${{ matrix.target.arch }}

    - name: Build Yosys package
      working-directory: mingw-w64-yosys
      run: |
        tries=0
        # Try building three times due to the arbitrary 'Bad address' error
        while [ $tries -lt 3 ]; do
          makepkg-mingw --noconfirm --noprogressbar -sCLfc
          pacman -U --noconfirm mingw-w64-*-any.pkg.tar.* && exit 0
          tries=$((tries+1))
        done
        exit 1

    - name: Build SymbiYosys package
      working-directory: mingw-w64-python-sby
      run: |
        tries=0
        # Try building three times due to the arbitrary 'Bad address' error
        while [ $tries -lt 3 ]; do
          makepkg-mingw --noconfirm --noprogressbar -sCLfc
          pacman -U --noconfirm mingw-w64-*-any.pkg.tar.* && exit 0
          tries=$((tries+1))
        done
        exit 1

    - name: Build Cocotb package
      working-directory: mingw-w64-python-cocotb
      run: |
        tries=0
        # Try building three times due to the arbitrary 'Bad address' error
        while [ $tries -lt 3 ]; do
          makepkg-mingw --noconfirm --noprogressbar -sCLfc
          pacman -U --noconfirm mingw-w64-*-any.pkg.tar.* && exit 0
          tries=$((tries+1))
        done
        exit 1

    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        path: mingw-w64-*/mingw-*.pkg.tar.zst

  release:
    needs:
      - msys2
    runs-on: windows-latest
    if: startsWith(github.ref, 'refs/tags/')

    steps:
      - name: Download artifact
        id: download_artifact
        uses: actions/download-artifact@v3

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          body: |
            Release ${{ github.ref }}
      
      - run: ls -R ${{ steps.download_artifact.outputs.download_path }}

      - name: Upload files
        id: upload
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          files: |
            artifact/mingw-*/mingw-*.tar.zst